In [4]:
import os
import pandas as pd

# Specify the directory containing the CSV files
directory = '/home/marycamila/flaresat/source/viirs'

# List to hold all DataFrames
df_list = []

# Loop through all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        file_path = os.path.join(directory, filename)
        df = pd.read_csv(file_path)  # Read each CSV file
        df = df[["Lat_GMTCO", "Lon_GMTCO", "Date_Mscan", "Temp_BB"]]
        df_list.append(df)  # Append each DataFrame to the list

# Concatenate all DataFrames in the list into a single DataFrame
final_df = pd.concat(df_list, ignore_index=True)

# Display the resulting DataFrame
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22858641 entries, 0 to 22858640
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   Lat_GMTCO   float64
 1   Lon_GMTCO   float64
 2   Date_Mscan  object
 3   Temp_BB     int64
dtypes: float64(2), int64(1), object(1)
memory usage: 697.6+ MB

In [5]:
final_df.head()

   Lat_GMTCO  Lon_GMTCO               Date_Mscan  Temp_BB
0 -10.013559  46.884789  2019/05/11 21:22:30.437   999999
1 -13.469957  67.704781  2019/05/11 21:22:33.995   999999
2 -13.660327  68.336235  2019/05/11 21:22:35.775   999999
3 -11.121411  49.964245  2019/05/11 21:22:39.333   999999
4 -11.607000  51.957069  2019/05/11 21:22:42.892   999999

In [6]:
final_df["Month"] = pd.to_datetime(final_df["Date_Mscan"]).dt.month

In [7]:
final_df = final_df[final_df["Temp_BB"] != 999999]

In [8]:
final_df.groupby("Month").size().reset_index(name="count").sort_values("count", ascending=False)

    Month   count
7     8.0  619891
11   12.0  589015
8     9.0  579112
2     3.0  534465
0     1.0  520166
6     7.0  511663
1     2.0  494421
3     4.0  479474
10   11.0  478142
9    10.0  434341
4     5.0  402222
5     6.0  355932

In [9]:
final_df.to_csv("/home/marycamila/flaresat/source/viirs/2019_vnf_processed.csv", index=False)